export interface ActiveUser {
  role: 'admin' | 'employee';
  fullName: string;
  personnelCode?: string;
  storeBranch?: string;
  employeeRole?: string;
}

export interface Employee {
  id: string;
  personnelCode: string;
  nationalCode: string;
  fullName: string;
  storeBranch: string; // Acts as service_location_title
  role: string;        // Acts as access level ('کارشناس پاسخگو' | 'پرسنل عادی')
  jobTitle?: string;   // Acts as job_title / سمت
  phone?: string;
  department?: string;
  employmentDate?: string; // Solar Hijri date e.g. "1399/01/01"
  birthDate?: string;      // Solar Hijri date e.g. "1368/07/24"
  createdAt: string;
}

export type TicketStatus = 'unread' | 'read' | 'unanswered' | 'answered' | 'in_progress';

export interface AdminNotification {
  id: string;
  type: 'new_ticket' | 'new_reply' | 'status_change';
  ticketId: string;
  ticketTitle: string;
  message: string;
  read: boolean;
  createdAt: string;
}

export interface Message {
  id: string;
  sender: 'user' | 'admin';
  senderName: string;
  text: string;
  createdAt: string;
  voiceData?: string[]; // Array of base64 audio strings (data:audio/webm;base64,...)
}

export interface InternalNote {
  id: string;
  author: string;
  text: string;
  createdAt: string;
}

export interface Ticket {
  id: string; // This will also act as the tracking code (کد رهگیری)
  title: string;
  category: string;
  subcategory: string;
  description: string;
  status: TicketStatus;
  confidential: boolean; // محرمانه
  isAnonymous: boolean;
  personnelCode?: string; // Present if not anonymous
  employeeName?: string;  // Present if not anonymous
  storeBranch?: string;   // Present if not anonymous
  createdAt: string;
  updatedAt: string;
  messages: Message[];
  internalNotes: InternalNote[];
  aiSummary?: string; // Summary generated by Gemini API
  aiSuggestedReply?: string; // Suggested reply generated by Gemini API
}

export interface Category {
  name: string;
  subcategories: string[];
}

export const STANDARD_CATEGORIES: Category[] = [
  {
    name: 'آزار فیزیکی',
    subcategories: [
      'نزدیکی بیش از حد فیزیکی',
      'تماس بدنی ناخواسته',
      'رفتارهای تهدیدآمیز فیزیکی',
      'سایر موارد آزار فیزیکی'
    ]
  },
  {
    name: 'آزار کلامی و روانی',
    subcategories: [
      'شوخی‌های نامناسب یا جنسی',
      'توهین، تحقیر یا تمسخر کلامی',
      'تهدید به اخراج، جریمه یا تنزل رتبه بی‌مورد',
      'فشار روانی و ایجاد محیط کار سمی'
    ]
  },
  {
    name: 'آزار سایبری و دیجیتال',
    subcategories: [
      'ارسال پیام، عکس یا محتوای نامناسب در شبکه‌های اجتماعی',
      'درخواست‌های مکرر شخصی و مزاحمت دیجیتال خارج از ساعت کاری',
      'شایعه‌پراکنی آنلاین یا اشتراک اطلاعات خصوصی'
    ]
  },
  {
    name: 'تبعیض و قلدری سازمانی',
    subcategories: [
      'تبعیض جنسیتی، قومی یا مذهبی',
      'جلوگیری از ارتقاء یا تضییع حقوق مصوب',
      'بایکوت سازمانی یا قلدری گروهی (Mobbing)'
    ]
  },
  {
    name: 'تخلفات مالی و سوء استفاده',
    subcategories: [
      'سوء استفاده از قدرت و جایگاه شغلی برای منافع شخصی',
      'پیشنهاد رشوه، تبانی یا اختلاس',
      'درخواست فعالیت‌های غیرقانونی یا خارج از آیین‌نامه دیلی مارکت'
    ]
  },
  {
    name: 'مشکلات عملیاتی و رفاهی',
    subcategories: [
      'عدم رعایت دستورالعمل‌های ایمنی و بهداشتی فروشگاه',
      'تجهیزات فرسوده یا شرایط کار ناایمن در شعبه',
      'مشکلات شدید رفاهی پرسنل (ساعت کار، مرخصی، بیمه)'
    ]
  }
];
